flaskr/__init__.py
import os
from flask import Flask, render_template, request

def create_app(test_config=None):
    # Create and configure app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite')

    )

    if test_config is None:
        # Load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # Load the test config if passed in
        app.config.from_mapping(test_config)
    
    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    

    from . import db
    db.init_app(app)

    from . import auth
    app.register_blueprint(auth.auth)

    from . import views
    app.register_blueprint(views.views)




    return app

flaskr/auth.py
import functools
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from werkzeug.security import check_password_hash, generate_password_hash

from flaskr.db import get_db

auth = Blueprint('auth', __name__, url_prefix='/auth')

@auth.route('/register', methods=["GET", "POST"])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        passwordConfirm = request.form['passwordConfirm']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required'
        elif not password:
            error = 'Password is required'
        elif password != passwordConfirm:
            error = 'Passwords must match'

        if error is None:
            try:
                db.execute(
                    'INSERT INTO user (username, password) VALUES (?, ?)',
                    (username, generate_password_hash(password),)
                )
                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for('auth.login'))
        
        flash(error)
    
    return render_template('auth/register.html')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method =='POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()
        
        if user is None:
            error = 'Incorrect username'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password'
        
        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('views.index'))
        
        flash(error)

    return render_template('auth/login.html')

@auth.route('logout')
def logout():
    session.clear()
    return redirect(url_for('views.index'))


@auth.before_app_request
def load_logged_in_user():
    user_id = [session.get('user_id')]

    if user_id is None:
        g.user = None
    
    else: 
        g.user = get_db().execute(
        'SELECT * FROM user WHERE id = ?', (user_id)
        ).fetchone()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        
        return view(**kwargs)
    return wrapped_view

flaskr/views.py
from flask import (
    Blueprint, redirect, render_template, request, session, url_for, flash
)

import sqlite3

from flaskr.db import get_db

from .auth import login_required

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def index():
    if request.method == 'POST':
        db = get_db()
        error = None

        # Get the submitted amount of recipes
        amountToGenerate = request.form['amountToGenerate']

        if int(amountToGenerate) < 1 or int(amountToGenerate) > 5:
            error = "Vul een nummer van 1 tot 5 in."
            flash(error)
            return render_template('index.html')

        # TODO: Implement Flash messages if the input isn't correct
        query = db.execute(
            'SELECT * FROM recipes ORDER BY RANDOM() LIMIT ?;',
            (amountToGenerate)
        )

        return render_template('index-generated.html', query=query)
    else:
        return render_template('index.html')

@views.route('/add-recipe', methods=['GET', 'POST'])
@login_required
def addRecipe():
    if request.method == 'POST':
        recipeName = request.form['recipeName']
        recipeRating = request.form['recipeRating']
        url = request.form['url']
        recipeAuthor = request.form['recipeAuthor']
        recipeRating = request.form['recipeRating']
        submittedBy = request.form['submittedBy']

        error = None
        db = get_db()

        if not recipeName:
            error = 'Voeg de naam van het recept toe.'
        if not recipeRating:
            error = 'Geef een rating aan het recept.'
        if int(recipeRating) < 1 or int(recipeRating) > 5:
            error = 'Geef een rating tussen 1 en 5.'
        if not url:
            error = 'Voeg een geldige url van het recept toe.'
        if not recipeAuthor:
            error = 'Voeg een geldige auteur toe.'

        if error is None:
            try:
                db.execute(
                    'INSERT INTO recipes (submitted_by, name, author, rating, url) VALUES (?, ?, ?, ?, ?)',
                    (submittedBy, recipeName, recipeAuthor, recipeRating, url)
                )
                db.commit()
            except db.IntegrityError:
                error = "Recipe is already registered."           
            else:
                flash(f'{recipeName} werd succesvol toegevoegd aan de database!')
                return redirect(url_for('views.addRecipe'))


        flash(error)
        return render_template('addRecipe.html')



    else:
        db = get_db()
        cursor = db.cursor()
        cursor.execute('SELECT * FROM user;')
        query = cursor.fetchall()

        for row in query:
            print(row['id'])

        return render_template('addRecipe.html', query=query)

@views.route('/all-recipes')
@login_required
def allRecipes():
    db = get_db()

    query = db.execute(
        'SELECT * FROM recipes;'
    )

    return render_template('allRecipes.html', query=query)

@views.errorhandler(404)
def page_not_found(error):
    return render_template('pageNotFound.html'), 404

flaskr/templates/addRecipe.html
{% extends "layout.html" %}

{% block title %}
    Recept toevoegen
{% endblock %}

{% block body %}
    <h1>Voeg een recept toe aan de database</h1>
    
    <form action="{{ url_for('views.addRecipe') }}" method="POST">

        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="recipeName" autofocus placeholder="Naam van het recept" required>
            <label for="recipeName">Naam van het recept</label>
        </div>


        <div class="form-floating mb-3">
            <input type="number" class="form-control" name="recipeRating" autofocus placeholder="Geef een score van 1 tot 5" required>
            <label for="recipeRating">Score van 1 tot 5</label>
        </div>

        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="url" placeholder="Typ hier de link naar het recept">
            <label for="url">Link naar het recept</label>
        </div>
        
        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="recipeAuthor" placeholder="Van wie is het recept?">
            <label for="recipeAuthor">Auteur van het recept</label>

        </div>

        <!-- Add user ID to submitted recipe -->
        <input type="text"  name="submittedBy" hidden value="{{ g.user['id'] }}">
        

        <input type="submit" class="btn btn-danger" value="Voeg dit recept toe!">

    </form>

{% endblock %}

flaskr/templates/allRecipes.html
{% extends "layout.html" %}
{% import "macros.html" as macros %}

{% block title %}
    Alle recepten
{% endblock %}

{% block body %}
    <h1>Dit zijn alle recepten in de database:</h1>


    <div class="container">
        <div class="row">
            {% for row in query %}
            {% set rating = row['rating'] %}
            <div class="col-lg-4 col-md-6 col-sm-12 mb-3">
                <div class="card h-100">
                    <div class="card-body d-flex flex-wrap">
                        <div class="w-100">
    
                            <h2 class="card-title fs-4">{{ row['name'] }}</h2>
                            <p class="mb-5">Recept door: {{ row['author'] }}</p>
    
                        </div>
                        
                        <div class="align-self-end w-100">
    
                            <p> Rating:                           
                                {% for star in range(rating) %}
                                    &starf;
                                {% endfor %}
    
                                {% for nostar in range(5 - rating) %}
                                    &star;
                                {% endfor %}
                            </p>
    
                            <a href="{{ row['url'] }}" class="card-link btn btn-danger" target="_blank">Bekijk recept</a>
    
                        </div>
                    </div>        
                </div>
                
            </div>
            {% endfor %}
        </div>
    </div>
    



{% endblock %}

flaskr/templates/boilerplate.html
{% extends "layout.html" %}

{% block title %}
    <!-- TITLE HERE-->
{% endblock %}

{% block body %}
    <!-- BODY HERE -->
{% endblock %}

flaskr/templates/index-generated.html
{% extends "layout.html" %}
{% block title %}
    Foodplanner
{% endblock %}

{% block body %}
    
    <h1>Dit zijn jouw voorgestelde recepten!</h1>

    <div class="container">
        <div class="row">
            {% for row in query %}
            {% set rating = row['rating'] %}
            <div class="col-lg-4 col-md-6 col-sm-12 mb-3">
                <div class="card h-100">
                    <div class="card-body d-flex flex-wrap">
                        <div class="w-100">
    
                            <h2 class="card-title fs-4">{{ row['name'] }}</h2>
                            <p class="mb-5">Recept door: {{ row['author'] }}</p>
    
                        </div>
                        
                        <div class="align-self-end w-100">
    
                            <p> Rating:                           
                                {% for star in range(rating) %}
                                    &starf;
                                {% endfor %}
    
                                {% for nostar in range(5 - rating) %}
                                    &star;
                                {% endfor %}
                            </p>
    
                            <a href="{{ row['url'] }}" class="card-link btn btn-danger" target="_blank">Bekijk recept</a>
    
                        </div>
                    </div>        
                </div>
                
            </div>
            {% endfor %}
        </div>
    </div>


    <h2 class="mt-5">Genereer nieuwe recepten</h2>
    <form action="{{ url_for('views.index') }}" method="POST">

        <div class="mb-3 w-50 d-flex form-floating">
            <input type="number" class="form-control me-2" name="amountToGenerate">
            <label for="amountToGenerate">Hoeveel recepten wil je genereren?</label>
            <input type="submit" class="btn btn-danger" value="Opnieuw proberen!">
        </div>

    </form>
{% endblock %}

flaskr/templates/index.html
{% extends "layout.html" %}
{% block title %}
    Foodplanner
{% endblock %}

{% block body %}
    <h1 class="text-center">Hoeveel recepten wil je zien?</h1>
    <form action="{{ url_for('views.index') }}" method="POST" class="d-flex flex-column form-floating w-50 mx-auto mb-2">


            <input type="number" class="form-control" name="amountToGenerate">

            <label for="amountToGenerate">Typ een nummer van 1 tot 5</label>

            <input type="submit" class="btn btn-danger w-100 mt-3" value="Toon me de recepten 🧙‍♂️">

    </form>


    <p class="text-center">Alle recepten worden random gekozen uit de <a href="{{ url_for('views.allRecipes') }}">volledige database</a>.</p>

{% endblock %}

flaskr/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
        
        <!-- Link Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
         <!-- Link stylesheet -->
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('views.index') }}" id="navbar-title">Foodplanner</a>
          
          <!-- Show navbar navigation if user is logged in-->
          {% if g.user %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.addRecipe') }}">Recept toevoegen</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.allRecipes') }}">Alle recepten</a>
              </li>
            </ul>
            {% endif %}

            <!-- Right aligned list in navbar -->

            <div>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <!-- If user is logged in-->
                {% if g.user %}
                <li class="nav-item">
                  <span class="nav-link disabled">Ingelogd als {{ g.user['username'] }}</span>
                </li>
  
                <li class="nav-item">
                  <a href="{{ url_for('auth.logout') }}" class="nav-link">Log out</a>
                </li>
  
                <!-- If user is logged out -->
                {% else %}
  
                <li class="nav-item">
                  <a href="{{ url_for('auth.register') }}" class="nav-link">Registreren</a>
                </li>
  
                <li class="nav-item">
                  <a href="{{ url_for('auth.login') }}" class="nav-link">Inloggen</a>
                </li>
  
                {% endif %}
  
              </ul>
            </div>
          </div>
        </div>
      </nav>

      {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
      {% endfor %}

        <main>
            {% block body %}{% endblock %}
        </main>
        <footer>
          A project by <a href="https://opmijntalloor.be">Op Mijn Talloor</a>
        </footer>

        <!-- Link Bootstrap Script -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> 
    </body>
</html>

flaskr/templates/macros.html
{% macro generateRecipes() -%}

<div class="container">
    <div class="row">
        {% for row in query %}
        {% set rating = row['rating'] %}
        <div class="col-lg-4 col-md-6 col-sm-12 mb-3">
            <div class="card h-100">
                <div class="card-body d-flex flex-wrap">
                    <div class="w-100">

                        <h2 class="card-title fs-4">{{ row['name'] }}</h2>
                        <p class="mb-5">Recept door: {{ row['author'] }}</p>

                    </div>
                    
                    <div class="align-self-end w-100">

                        <p> Rating:                           
                            {% for star in range(rating) %}
                                &starf;
                            {% endfor %}

                            {% for nostar in range(5 - rating) %}
                                &star;
                            {% endfor %}
                        </p>

                        <a href="{{ row['url'] }}" class="card-link btn btn-danger" target="_blank">Bekijk recept</a>

                    </div>
                </div>        
            </div>
            
        </div>
        {% endfor %}
    </div>
</div>

{%- endmacro -%}

{% macro test() -%}
<p>Test</p>
{%- endmacro -%}

flaskr/templates/pageNotFound.html
{% extends "layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Sorry, deze pagina bestaat niet.</h1>
{% endblock %}